name: CD

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run make4ht
      uses: docker://ghcr.io/michal-h21/make4ht-action:latest
      env:
        command: "sudo apt-get install texlive-fonts-extra; make website"
    - name: Publish the web pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./out
